#!/usr/bin/env ruby

require_relative 'slack'
require_relative 'slack_config'
require_relative 'slack_options'
require_relative 'tmate'

tmate_address = TMate.my_session_address
if !tmate_address
  puts "You are not in a tmate session"
  exit 1
end

options = SlackOptions.new(SlackConfig.load)
options.add_opt_on('-p', '--prefix [INVITE_MSG]', 'prefix', :prefix)
exit 1 if !options.parse!

slack = Slack.new(options)

text="#{options[:prefix]} <ssh://#{tmate_address}|tmate session>"
author=`whoami`.strip!

slack.send_all(text, author)
